require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  NewCops: enable
Layout/LineLength:
  Enabled: false
Lint/RedundantSafeNavigation:
  Enabled: false
Metrics/AbcSize:
  IgnoredMethods:
    - tag
Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Max: 20
Rails/HasAndBelongsToMany:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: false
